const express = require('express');
const router = express.Router();
const nodemailer = require('nodemailer');

router.post('/', async (req, res) => {
  const { name, email, message } = req.body;

  if (!name || !email || !message) {
    return res.status(400).json({ message: 'Please provide name, email, and message.' });
  }

  try {
    const smtpPort = parseInt(process.env.SMTP_PORT || '587', 10);
    // Configure nodemailer with Gmail SMTP details from environment variables
    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST || 'smtp.gmail.com',
      port: smtpPort,
      secure: smtpPort === 465, // true for 465, false for other ports
      auth: {
        user: process.env.SMTP_USER, 
        pass: process.env.SMTP_PASS,
      },
    });

    // Setup email data
    const mailOptions = {
      from: `Portfolio Contact Form <${process.env.SMTP_USER}>`, 
      replyTo: `${name} <${email}>`, 
      to: process.env.SMTP_USER, 
      subject: `New Portfolio Contact from ${name}`, 
      text: `You have received a new message from your portfolio contact form.\n\nName: ${name}\nEmail: ${email}\n\nMessage:\n${message}`,
      html: `
        <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; max-width: 600px; margin: 0 auto; background-color: #f8fafc; padding: 20px; border-radius: 8px;">
          <div style="background-color: #2563EB; color: #ffffff; padding: 20px; border-radius: 8px 8px 0 0; text-align: center;">
            <h2 style="margin: 0;">🚀 New Portfolio Message</h2>
            <p style="margin: 5px 0 0 0; font-size: 14px; opacity: 0.9;">Someone reached out from your website</p>
          </div>
          
          <div style="background-color: #ffffff; padding: 30px; border-radius: 0 0 8px 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.05);">
            <div style="margin-bottom: 20px;">
              <p style="font-size: 12px; color: #64748b; text-transform: uppercase; font-weight: bold; letter-spacing: 1px; margin: 0 0 5px 0;">From</p>
              <p style="font-size: 16px; color: #0f172a; margin: 0; font-weight: 600;">${name}</p>
            </div>
            
            <div style="margin-bottom: 20px;">
              <p style="font-size: 12px; color: #64748b; text-transform: uppercase; font-weight: bold; letter-spacing: 1px; margin: 0 0 5px 0;">Email</p>
              <p style="font-size: 16px; margin: 0;"><a href="mailto:${email}" style="color: #2563EB; text-decoration: none;">${email}</a></p>
            </div>
            
            <div style="margin-top: 30px;">
              <p style="font-size: 12px; color: #64748b; text-transform: uppercase; font-weight: bold; letter-spacing: 1px; margin: 0 0 10px 0;">Message</p>
              <div style="background-color: #f1f5f9; padding: 20px; border-left: 4px solid #2563EB; border-radius: 4px; color: #334155; font-size: 15px; line-height: 1.6; white-space: pre-wrap;">${message}</div>
            </div>
          </div>
          
          <div style="text-align: center; margin-top: 20px; font-size: 12px; color: #94a3b8;">
            <p>This email was automatically generated by your portfolio contact form.</p>
          </div>
        </div>
      `,
    };

    // Send mail with defined transport object
    const info = await transporter.sendMail(mailOptions);
    console.log('Message sent: %s', info.messageId);

    res.status(200).json({ message: 'Message sent successfully!' });
  } catch (error) {
    console.error('Error sending email:', error);
    res.status(500).json({ message: 'Failed to send message. Please try again later.' });
  }
});

module.exports = router;
